# Generated by Django 3.2.5 on 2021-11-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=20)),
                ('studentUsn', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=20)),
            ],
        ),
    ]
